#!/bin/bash
pdflatex --output-directory ../pdf ClintonThesisFinal.tex
cd ../pdf
bash buildFinal
cd ../tex
pdflatex --output-directory ../pdf ClintonThesisFinal.tex
pdflatex --output-directory ../pdf ClintonThesisFinal.tex
