#!/bin/bash
pdflatex --output-directory ../../pdf dec6.tex
pdflatex --output-directory ../../pdf dec6.tex
pdflatex --output-directory ../../pdf dec6.tex

#pdflatex --output-directory ../../pdf thesisDefense.tex
#pdflatex --output-directory ../../pdf thesisDefense.tex
#pdflatex --output-directory ../../pdf thesisDefense.tex